stages:
  - deploy

image: ${DOCKER_DEPLOY_IMAGE_NAME}:${DOCKER_DEPLOY_IMAGE_TAG}

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  STACK: elastic
  IMAGE_TAG: 1.1.0rc1

deploy-supporting-branch-develop:
  stage: deploy
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICES_TO_CHECK: ${STACK}_elasticsearch-exporter
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.dev.yml
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
  script:
    - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH} ES_AUTH=${ES_AUTH} ES_HOST=${ES_HOST} ES_ALL=${ES_ALL}
      ES_CLUSTER_SETTINGS=${ES_CLUSTER_SETTINGS} ES_INDICES=${ES_INDICES} ES_INDICES_SETTINGS=${ES_INDICES_SETTINGS}
      ES_SHARDS=${ES_SHARDS} ES_SHARDS_SETTINGS=${ES_SHARDS_SETTINGS} ES_SNAPSHOTS=${ES_SNAPSHOTS}
      ES_TIMEOUT=${ES_TIMEOUT} ES_CLUSTERINFO_INTERVAL=${ES_CLUSTERINFO_INTERVAL}
  environment:
    name: dev
  only:
    - branches
  except:
    - master
  when: manual

deploy-stable-branch-develop:
  stage: deploy
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICES_TO_CHECK: ${STACK}_elasticsearch-exporter
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.dev.yml
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
  script:
    - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH} ES_AUTH=${ES_AUTH} ES_HOST=${ES_HOST} ES_ALL=${ES_ALL}
      ES_CLUSTER_SETTINGS=${ES_CLUSTER_SETTINGS} ES_INDICES=${ES_INDICES} ES_INDICES_SETTINGS=${ES_INDICES_SETTINGS}
      ES_SHARDS=${ES_SHARDS} ES_SHARDS_SETTINGS=${ES_SHARDS_SETTINGS} ES_SNAPSHOTS=${ES_SNAPSHOTS}
      ES_TIMEOUT=${ES_TIMEOUT} ES_CLUSTERINFO_INTERVAL=${ES_CLUSTERINFO_INTERVAL}
  environment:
    name: dev
  only:
    - master
  when: manual

deploy-supporting-branch-production:
  stage: deploy
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICES_TO_CHECK: ${STACK}_elasticsearch-exporter
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.prod.yml
    PUBLIC_HOSTNAME: ${PRO_PUBLIC_HOSTNAME}
  script:
     - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH} ES_AUTH=${ES_AUTH} ES_HOST=${ES_HOST} ES_ALL=${ES_ALL}
      ES_CLUSTER_SETTINGS=${ES_CLUSTER_SETTINGS} ES_INDICES=${ES_INDICES} ES_INDICES_SETTINGS=${ES_INDICES_SETTINGS}
      ES_SHARDS=${ES_SHARDS} ES_SHARDS_SETTINGS=${ES_SHARDS_SETTINGS} ES_SNAPSHOTS=${ES_SNAPSHOTS}
      ES_TIMEOUT=${ES_TIMEOUT} ES_CLUSTERINFO_INTERVAL=${ES_CLUSTERINFO_INTERVAL}
  environment:
    name: pro
  only:
    - branches
  except:
    - master
  when: manual

deploy-stable-branch-production:
  stage: deploy
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICES_TO_CHECK: ${STACK}_elasticsearch-exporter
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.prod.yml
    PUBLIC_HOSTNAME: ${PRO_PUBLIC_HOSTNAME}
  script:
     - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH} ES_AUTH=${ES_AUTH} ES_HOST=${ES_HOST} ES_ALL=${ES_ALL}
      ES_CLUSTER_SETTINGS=${ES_CLUSTER_SETTINGS} ES_INDICES=${ES_INDICES} ES_INDICES_SETTINGS=${ES_INDICES_SETTINGS}
      ES_SHARDS=${ES_SHARDS} ES_SHARDS_SETTINGS=${ES_SHARDS_SETTINGS} ES_SNAPSHOTS=${ES_SNAPSHOTS}
      ES_TIMEOUT=${ES_TIMEOUT} ES_CLUSTERINFO_INTERVAL=${ES_CLUSTERINFO_INTERVAL}
  environment:
    name: pro
  only:
    - master
  when: manual
