version: '3.5'

services:
  elasticsearch-exporter:
    image: ${IMAGE_NAME:-quay.io/prometheuscommunity/elasticsearch-exporter}:${IMAGE_TAG:-latest}
    environment:
      ES_URI: ${ES_PROTOCOL}://${ES_USER}:${ES_PASS}@${ES_HOST}:${ES_PORT}
      WEB_LISTEN_ADDRESS: :${UI_PORT}
      ES_ALL:
      ES_CLUSTER_SETTINGS:
      ES_INDICES:
      ES_INDICES_SETTINGS:
      ES_SHARDS:
      ES_SNAPSHOTS:
      ES_TIMEOUT:
      ES_CLUSTERINFO_INTERVAL:
      ES_SSL_SKIP_VERIFY:
    networks:
      elastic-net:
      metric-net:
    healthcheck:
      test: wget --spider http://localhost:${UI_PORT}
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-15s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-256M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-128M}

networks:
  elastic-net:
    name: ${ELASTIC_NET_NAME:-elastic-net}
    driver: ${ELASTIC_NET_DRIVER:-overlay}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true
