version: '3.5'

services:
  elasticsearch-exporter:
    image: ${IMAGE_NAME:-justwatch/elasticsearch_exporter}:${IMAGE_TAG:-1.1.0rc1}
    environment:
      - ES_URI=${ES_PROTOCOL}://${ES_USER}:${ES_PASS}@${ES_HOST}:${ES_PORT}
      - ES_ALL
      - ES_CLUSTER_SETTINGS
      - ES_INDICES
      - ES_INDICES_SETTINGS
      - ES_SHARDS
      - ES_SHARDS_SETTINGS
      - ES_SNAPSHOTS
      - ES_TIMEOUT
      - ES_CLUSTERINFO_INTERVAL
      - ES_SSL-SKIP-VERIFY
      - WEB_LISTEN-ADDRESS
    networks:
      - elastic-net
      - metric-net
      - traefik-net
    healthcheck:
      test: wget --spider http://localhost:${WEB_LISTEN-ADDRESS}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:${UI_SUBDOMAIN}.${PUBLIC_HOSTNAME}
        traefik.backend: elasticsearch-exporter
        traefik.port: "${WEB_LISTEN-ADDRESS}"
      restart_policy:
        delay: 30s
        window: 1m
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          memory: 205M

networks:
  elastic-net:
    name: ${ELASTIC_NET_NAME:-elastic-net}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true
